from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

s=Service('C:/Users/nadin/Downloads/chromedriver_win32/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.get('https://guru.qahacking.ru')
time.sleep(2)
driver.set_window_size(1366,768)
driver.find_element(By.XPATH, "/html/body/div/div[2]/div[1]/div/div/nav/div[2]/ul/li[3]/a").click()
driver.find_element(By.XPATH, "/html/body/div/div[2]/div[1]/div/div/nav/div[2]/ul/li[3]/a").click()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div[3]/div/div[1]/div[1]/div/div/div[3]/div[7]/a[1]").click()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/form/table[1]/tbody/tr[2]/td[4]/div[2]/input").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/form/table[1]/tbody/tr[2]/td[4]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/form/table[1]/tbody/tr[2]/td[4]/div[2]/input").send_keys(2)
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/form/table[1]/tbody/tr[2]/td[4]/div[2]/span/img").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/form/div[2]/div/div[2]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[1]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[1]/div[2]/input").send_keys("Иван")
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[2]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[2]/div[2]/input").send_keys("Иванов")
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[3]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[3]/div[2]/input").send_keys("mail@mail.ru")
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[4]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[4]/div[2]/input").send_keys("Чистопольская,73")
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[5]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[5]/div[2]/input").send_keys("420001")
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[6]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[6]/div[2]/input").send_keys("Казань")
driver.find_element(By.ID, "country").click()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[8]/div[2]/select/option[177]").click()
driver.find_element(By.ID, "country").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[9]/div[2]/input").clear()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[1]/div[9]/div[2]/input").send_keys("89196295795")
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[2]/div[2]/input[1]").click()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div[4]/div/input").click()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div/div[3]/label/b").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/input").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/div/div[2]/input").click()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div/form/input").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div[2]/form/div/div[3]/input").click()
driver.find_element(By.XPATH, "/html/body/div/div[3]/div/div[2]/div[2]/form/div/div[4]/input").click()
time.sleep(10)


